### ISSUE TITLE
file ingestor: panic with pcap ip fragmentation

### ISSUE THREAD

**Issue by dmachard** [dmachard/go-dns-collector#240]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x98a782]

goroutine 28 [running]:
github.com/dmachard/go-dnscollector/collectors.(*FileIngestor).ProcessPcap(0xc0003400f0, {0xc0001a4a20, 0x2b})
        /home/denis/Lab/github.com/go-dns-collector/collectors/file_ingestor.go:222 +0x6c2
created by github.com/dmachard/go-dnscollector/collectors.(*FileIngestor).Run
        /home/denis/Lab/github.com/go-dns-collector/collectors/file_ingestor.go:371 +0xa1d
exit status 2

**Comment by dmachard** [comment]
Implemented in release v0.30.0.
